apiVersion: v1
kind: Service
metadata:
  name: {{ include "LyftClient.fullname" . }}-redis
  labels:
    {{- include "LyftClient.labels" . | nindent 4 }}
    app: redis
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis
    - port: 6380
      targetPort: 6380
      protocol: TCP
      name: redis-tls
  selector:
    {{- include "LyftClient.selectorLabels" . | nindent 4 }}
    app: redis
