apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: lyft-redis
    namespace: client
spec:
    serviceName: lyft-redis
    replicas: 3
    selector:
        matchLabels:
            app: lyft-redis
    template:
        metadata:
            labels:
                app: lyft-redis
        spec:
            initContainers:
                - name: lyft-redis-config
                  image: redis:6.2.3-alpine
                  command: ["sh", "-c"]
                  args:
                      - |
                          cp /tmp/redis/redis.conf /etc/redis/redis.conf

                          echo "finding master..."
                          MASTER_FDQN=`hostname  -f | sed -e 's/redis-[0-9]\./redis-0./'`
                          if [ "$(redis-cli -h sentinel -p 5000 ping)" != "PONG" ]; then
                            echo "master not found, defaulting to redis-0"

                            if [ "$(hostname)" == "redis-0" ]; then
                              echo "this is redis-0, not updating config..."
                            else
                              echo "updating redis.conf..."
                              echo "slaveof $MASTER_FDQN 6379" >> /etc/redis/redis.conf
                            fi
                          else
                            echo "sentinel found, finding master"
                            MASTER="$(redis-cli -h sentinel -p 5000 sentinel get-master-addr-by-name mymaster | grep -E '(^redis-\d{1,})|([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3})')"
                            echo "master found : $MASTER, updating redis.conf"
                            echo "slaveof $MASTER 6379" >> /etc/redis/redis.conf
                          fi
                  volumeMounts:
                      - name: lyft-redis-redis-config
                        mountPath: /etc/redis/
                      - name: lyft-redis-config
                        mountPath: /tmp/redis/
            containers:
                - name: lyft-redis
                  image: redis:7.0.5-alpine
                  command: ["redis-server"]
                  args: ["/etc/redis/redis.conf"]
                  ports:
                      - containerPort: 6379
                        name: redis
                  volumeMounts:
                      - name: data
                        mountPath: /data
                      - name: lyft-redis-config
                        mountPath: /etc/redis/
            volumes:
                - name: lyft-redis-redis-config
                  emptyDir: {}
                - name: lyft-redis-config
                  configMap:
                      name: lyft-redis-config
    volumeClaimTemplates:
        - metadata:
              name: lyft-redis-data
          spec:
              accessModes: ["ReadWriteOnce"]
              storageClassName: "local-storage"
              resources:
                  requests:
                      storage: 500Mi
